server:
  port: 8081
  # ?????undertow????????
  undertow:
    # ??IO???, ???????????,?????????, ??????CPU??????
    io-threads: 4
    # ???????, ?????servlet??????, undertow????????????,?????????????
    worker-threads: 20
    # ????????buffer,??buffer?????????IO??,????netty???????
    # ??buffer?????,???????????
    buffer-size: 1024
    # ?????????
    direct-buffers: true