server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 100
      min-spare: 10
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #开启GZIP压缩
  compression:
    enabled: true

spring:
  #  data:
  #    mongodb:
  #      host: 192.168.40.250
  #      port: 27017
  #      database: hono
  #      authentication-database: hono
  #      username: "hono"
  #      password: "123456"
  #      auto-index-creation: true
  #数据库配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    #基础配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 数据库链接地址，入股地址中数据名称需要动态替换，则数据库名称设置为 @dbname@
    url: jdbc:mysql://192.168.1.102:3306/hono?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
#        url: jdbc:postgresql://localhost:5432/hono?rewriteBatchedStatements=true
    hikari:
      minimum-idle: 10 #连接池中允许的最小连接数，默认10
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000(10分钟)
      maximum-pool-size: 100 #最大连接数，默认10
      auto-commit: true #自动提交
      pool-name: HikariCP #连接池名称
      max-lifetime: 1800000 #连接池生命周期(毫秒),超时而且没被使用则释放(retied), 默认30分钟，建议设置比数据库超时时长少30秒
      connection-timeout: 30000 # 数据库连接超时时间，默认30秒
  redis:
    host: 192.168.1.102
    port: 6379
    timeout: 20000
    password: 123456
    database: 0
  liquibase:
    enabled: false
redisson:
  #以下 redisson 的配置
  # sentinelMode 的可用值为，single/cluster/sentinel/master-slave
  sentinelMode: single
  #每个节点逗号分隔，如果是主从模式时，配置的第一个为主，其余为从
  address: redis://192.168.1.102:6379
  # 当mode等于sentinel使用
  masterName: myRedisMaster

#camunda.bpm:
#  admin-user:
#    id: root
#    password: 123456
#    firstName: root
#  filter:
#    create: All tasks
